### ISSUE TITLE
Misc suggestions

### ISSUE THREAD

**Issue by paulsohn** [rust-osdev/xhci#164]
Apologies for spamming bunch of issues.

- [ ] Mark capability registers as read-only.
    Currently they are read-write but they're supposed to be read-only according to the spec sheet.
- [ ] Rename `doorbell::Register` into `doorbell::Doorbell` (with an alias of `doorbell::Register`).
    There are lots of other registers and it is clearer to say `Doorbell` than to keep prefixing `doorbell::Register`.
- [ ] Chain-able context setters, just like register bitmap setters ( as in https://github.com/rust-osdev/xhci/issues/83 )

I'll add a PR if these changes are appropriate.

**Comment by toku-sa-n** [comment]
Agree with all three suggestions. Please go ahead with PRs.
