### ISSUE TITLE
About implementing Mapper

### ISSUE THREAD

**Issue by akiradeveloper** [rust-osdev/xhci#90]
This example leaves map/unmap unimplemented. Is it allowed to do so? At least it seems to me that it will panic in `Single::new`.

```rust
    /// #[derive(Clone)]
    /// struct MemoryMapper;
    /// impl Mapper for MemoryMapper {
    ///     unsafe fn map(&mut self, phys_base: usize, bytes: usize) -> NonZeroUsize {
    ///         unimplemented!()
    ///     }
    ///
    ///     fn unmap(&mut self, virt_base: usize, bytes: usize) {
    ///         unimplemented!()
    ///     }
    /// }
    ///
    /// let mapper = MemoryMapper;
    /// let r = unsafe { xhci::Registers::new(MMIO_BASE, mapper) };
```

https://github.com/rust-osdev/xhci/blob/main/src/registers/mod.rs

**Comment by toku-sa-n** [comment]
This is an example of how to call `Registers::new`, and you have to implement the correct mapper when you use it in the actual code. I'll add a note about this later.
